version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
     - app-network
    environment:
      - VITE_API_BASE_URL=http://backend:3000

networks:
  app-network:
    driver: bridge
